export const headings = [
	'Company Name',
	'Contact Number',
	'Date Started',
	'Persona Name',
	'1st call f/back',
	'Activity Status',
	'Location',
	'Area',
	'Visit Planned Date',
	'Visit Status',
];
export const data = [
	{
		'Company Name': 'ABC Company',
		'Contact Number': '03123456789',
		'Date Started': '12/12/2020',
		'Persona Name': 'Sernor',
		'1st call f/back': '1',
		'Activity Status': 'Current',
		Location: 'Lahore',
		Area: 'Gulberg',
		'Visit Planned Date': '05/06/2022',
		'Visit Status': 'Visited',
	},
	{
		'Company Name': 'XYZ Company',
		'Contact Number': '03123456789',
		'Date Started': '23/06/2019',
		'Persona Name': 'Allaska',
		'1st call f/back': '1',
		'Activity Status': 'Current',
		Location: 'Lahore',
		Area: 'Gulberg',
		'Visit Planned Date': '05/06/2022',
		'Visit Status': 'Visited',
	},
	{
		'Company Name': 'XYZ Company',
		'Contact Number': '03123456789',
		'Date Started': '12/12/2020',
		'Persona Name': 'Allaska',
		'1st call f/back': '1',
		'Activity Status': 'Current',
		Location: 'Lahore',
		Area: 'Gulberg',
		'Visit Planned Date': '05/06/2022',
		'Visit Status': 'Visited',
	},
];
